# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/repoNuevoNBDev',
                'doc_host': 'https://esandovalp.github.io',
                'git_url': 'https://github.com/esandovalp/repoNuevoNBDev',
                'lib_path': 'repoNuevoNBDev'},
  'syms': { 'repoNuevoNBDev.Tarea': { 'repoNuevoNBDev.Tarea.Tarea': ('tarea.html#tarea', 'repoNuevoNBDev/Tarea.py'),
                                      'repoNuevoNBDev.Tarea.Tarea.__init__': ('tarea.html#tarea.__init__', 'repoNuevoNBDev/Tarea.py'),
                                      'repoNuevoNBDev.Tarea.Tarea.__str__': ('tarea.html#tarea.__str__', 'repoNuevoNBDev/Tarea.py')},
            'repoNuevoNBDev.core': {'repoNuevoNBDev.core.foo': ('core.html#foo', 'repoNuevoNBDev/core.py')}}}
